# QED/SA product reward with reward-exponent conditioning.
data:
  env_dir: ./data/envs/example_5k/

reward:
  beta: "uniform(1,64)"
  moo_scalarization: mul
  moo_preferences: "dirichlet(1.5)"
  settings: {}

property_penalty:
  mw: 500
